version: "3.7"

networks:
  app-network:
    driver: bridge

services:

  server:
    image: adminko/test:backend
    command: /root/server
    ports:
      - "3000:3000"
    networks:
      - app-network

  client:
    build: ./php
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${SERVER_CONFIGURATION_PATH}:/etc/apache2/sites-available
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}
    depends_on:
      - composer
      - db
    networks:
      - app-network

  composer:
    image: composer:latest
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install --ignore-platform-reqs --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    networks:
      - app-network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
    networks:
      - app-network